#!/bin/sh

case "`uname -a`" in
    *Darwin*)
    	echo macosx
	;;
    *FreeBSD*)
    	echo unix
	;;
    *Linux*)
    	echo unix
	;;
    *NetBSD*)
    	echo unix
	;;
    *Cygwin*)
    	echo win
	;;
    *MING*)
    	echo win
	;;
esac
